### PR TITLE
Training programs -  view list and create

### PR DESCRIPTION
**Pull request by megcruzen**
# Description
Added ability to view list of upcoming training programs and to create a new program.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

1. `git fetch --all`
1. `git checkout meg-training-list`
1. Run BangazonWorkforce
1. Verify that you have Training Programs in your database and take note of each EndDate.
1. Insert new Training Program into the database with a date in the future.
   ```
   INSERT into TrainingProgram ([Name], StartDate, EndDate, MaxAttendees) 
   VALUES ('Testing All The Things', '14 June 2019', '15 June 2019', 10)
   ```
1. In browser, go to Training Programs and verify that only upcoming programs display.
1. Click on "Create Training Program" and verify that you can create a new program, and that it displays in the list once created.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by colebryant — APPROVED** [review]
New features work!

**Review by alagrad94 — COMMENTED** [review]
Looks good!

**Review by alagrad94 — APPROVED** [review]
Looks good!

**Review by leahhoefling — APPROVED** [review]
Everything works good!

**Pull request merged**
